version: '3.0'

services:
  app:
    container_name: nnergix-test-docker
    restart: on-failure
    build: ./
    ports:
      - 3000:3000
    links: 
      - mongodb
    environment:
      - "DOCKER_URL=${DOCKER_URL}"
  mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
